# Generated by Django 4.1.3 on 2022-11-14 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Audio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("index", models.PositiveIntegerField(verbose_name="순서")),
                ("text", models.CharField(max_length=80, verbose_name="오디오로 변환된 텍스트")),
                ("speed", models.PositiveIntegerField(verbose_name="오디오의 스피드")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="projects.project",
                        verbose_name="프로젝트",
                    ),
                ),
            ],
            options={
                "verbose_name": "오디오",
                "verbose_name_plural": "오디오",
            },
        ),
    ]
