# Generated by Django 4.1.3 on 2022-11-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_rename_project_title_project_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="index",
            field=models.PositiveIntegerField(unique=True, verbose_name="순서"),
        ),
    ]
