# Generated by Django 4.1.3 on 2022-11-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_alter_audio_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="audio",
            name="path",
            field=models.CharField(default="1", max_length=80, verbose_name="파일 경로"),
            preserve_default=False,
        ),
    ]
