# Generated by Django 4.1.3 on 2022-11-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_remove_audio_path"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="audio",
            options={
                "ordering": ["index"],
                "verbose_name": "오디오",
                "verbose_name_plural": "오디오",
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["index"],
                "verbose_name": "프로젝트",
                "verbose_name_plural": "프로젝트",
            },
        ),
    ]
